---
    - name: Create a directory Vector
      ansible.builtin.file: path=vector state=directory mode=0755
    - name: Download Vector
      ansible.builtin.get_url:
        url: "https://packages.timber.io/vector/0.21.0/vector-0.21.0-1.x86_64.rpm"
        dest: "./vector/vector-0.21.0-1.x86_64.rpm"
        mode: 0664
        timeout: 200
    - name: Install Vector
      become: true
      ansible.builtin.yum:
        name: "./vector/vector-0.21.0-1.x86_64.rpm"
    - name: Template config Vector
      ansible.builtin.template:
        src: templates/vector.yml.j2
        dest: vector.yml
        mode: "644"
        owner: "{{ ansible_user_id }}"
        group: "{{ ansible_user_gid }}"
        validate: vector validate --no-environment --config-yaml %s
     - name: Create systemd unit
      become: true
      ansible.builtin.template:
        src: templates/vector.service.j2
        dest: /etc/systemd/system/vector.service
        mode: "644"
        owner: "{{ ansible_user_id }}"
        group: "{{ ansible_user_gid }}"
     - name: Start Vector
      become: true
      ansible.builtin.systemd:
        name: vector
        state: started
        daemon_reload: true
 # tasks file for vector-role
